development:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: mina_test_509_development

test:
  adapter: test

staging:
  adapter: redis
  urll: <%= AppConfig.redis.url %>
  channel_prefix: mina_test_509_staging

production:
  adapter: redis
  url: <%= AppConfig.redis.url %>
  channel_prefix: mina_test_509_production
